---
- name: Ensure PostgreSQL users are present.
  postgresql_user:
    name: "{{ item.0.name }}"
    password: "{{ item.0.password | default(omit) }}"
    login_unix_socket: "{{ item.1 }}"
  loop: "{{ postgresql_users|zip(postgresql_unix_socket_directories) | list }}"
  no_log: "{{ postgres_users_no_log }}"
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  environment:
    PGOPTIONS: "{{ (postgresql_auth_method == 'scram-sha-256') | ternary('-c password_encryption=scram-sha-256', '') }}"
